//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionAssist
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artifact
    {
        public int A_id { get; set; }
        public byte[] artifacts { get; set; }
        public Nullable<int> Decision_id { get; set; }
        public Nullable<int> Dr_id { get; set; }
    }
}
