//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionAssist
{
    using System;
    using System.Collections.Generic;
    
    public partial class FunctReq
    {
        public int FR_id { get; set; }
        public string FR_name { get; set; }
        public string FR_desc { get; set; }
        public int Project_id { get; set; }
    }
}
