//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionAssist
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DAssistEntities : DbContext
    {
        public DAssistEntities()
            : base("name=DAssistEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DecisionQAimpact> DecisionQAimpacts { get; set; }
        public virtual DbSet<DecisionRepo> DecisionRepoes { get; set; }
        public virtual DbSet<DesignDecision> DesignDecisions { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<QualityAttribute> QualityAttributes { get; set; }
        public virtual DbSet<QualityGoal> QualityGoals { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Trace> Traces { get; set; }
    }
}
