//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionAssist
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityGoal
    {
        public int QG_id { get; set; }
        public int QA_id { get; set; }
        public int Project_id { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual QualityAttribute QualityAttribute { get; set; }
    }
}
